
[LibraryClasses.common.PEIM]
  UnitTestLib|UnitTestFrameworkPkg\Library\UnitTestLib\UnitTestLib.inf

[LibraryClasses.common.DXE_DRIVER]
  UnitTestLib|UnitTestFrameworkPkg\Library\UnitTestLib\UnitTestLib.inf

[LibraryClasses.common.DXE_SMM_DRIVER]
  UnitTestLib|UnitTestFrameworkPkg\Library\UnitTestLib\UnitTestLib.inf

[LibraryClasses.common.UEFI_DRIVER]
  UnitTestLib|UnitTestFrameworkPkg\Library\UnitTestLib\UnitTestLib.inf

[LibraryClasses.common.UEFI_APPLICATION]
  UnitTestLib|UnitTestFrameworkPkg\Library\UnitTestLib\UnitTestLib.inf
