
[LibraryClasses.ARM]
  AndroidBootImgLib|EmbeddedPkg\Library\AndroidBootImgLib\AndroidBootImgLib.inf
  FdtLib|EmbeddedPkg\Library\FdtLib\FdtLib.inf

[LibraryClasses.common.PEIM]
  NvVarStoreFormattedLib|EmbeddedPkg\Library\NvVarStoreFormattedLib\NvVarStoreFormattedLib.inf

[LibraryClasses.common.DXE_DRIVER]
  NvVarStoreFormattedLib|EmbeddedPkg\Library\NvVarStoreFormattedLib\NvVarStoreFormattedLib.inf
  PlatformHasAcpiLib|EmbeddedPkg\Library\PlatformHasAcpiLib\PlatformHasAcpiLib.inf

[LibraryClasses.common.DXE_RUNTIME_DRIVER]
  NvVarStoreFormattedLib|EmbeddedPkg\Library\NvVarStoreFormattedLib\NvVarStoreFormattedLib.inf

[LibraryClasses.common.DXE_SMM_DRIVER]
  NvVarStoreFormattedLib|EmbeddedPkg\Library\NvVarStoreFormattedLib\NvVarStoreFormattedLib.inf

[LibraryClasses.common]
  AcpiLib|EmbeddedPkg\Library\AcpiLib\AcpiLib.inf
  NorFlashInfoLib|EmbeddedPkg\Library\NorFlashInfoLib\NorFlashInfoLib.inf
  PrePiLib|EmbeddedPkg\Library\PrePiLib\PrePiLib.inf
  TimeBaseLib|EmbeddedPkg\Library\TimeBaseLib\TimeBaseLib.inf

[LibraryClasses.AARCH64]
  AndroidBootImgLib|EmbeddedPkg\Library\AndroidBootImgLib\AndroidBootImgLib.inf
  FdtLib|EmbeddedPkg\Library\FdtLib\FdtLib.inf
