
[LibraryClasses.common.DXE_DRIVER]
  ArmVirtPL031FdtClientLib|ArmVirtPkg\Library\ArmVirtPL031FdtClientLib\ArmVirtPL031FdtClientLib.inf
  ArmVirtTimerFdtClientLib|ArmVirtPkg\Library\ArmVirtTimerFdtClientLib\ArmVirtTimerFdtClientLib.inf
  PciPcdProducerLib|ArmVirtPkg\Library\FdtPciPcdProducerLib\FdtPciPcdProducerLib.inf
  KvmtoolRtcFdtClientLib|ArmVirtPkg\Library\KvmtoolRtcFdtClientLib\KvmtoolRtcFdtClientLib.inf

[LibraryClasses.common.DXE_RUNTIME_DRIVER]
  ArmVirtPL031FdtClientLib|ArmVirtPkg\Library\ArmVirtPL031FdtClientLib\ArmVirtPL031FdtClientLib.inf
  KvmtoolRtcFdtClientLib|ArmVirtPkg\Library\KvmtoolRtcFdtClientLib\KvmtoolRtcFdtClientLib.inf

[LibraryClasses.common.UEFI_DRIVER]
  PciPcdProducerLib|ArmVirtPkg\Library\FdtPciPcdProducerLib\FdtPciPcdProducerLib.inf

[LibraryClasses.common]
  KvmtoolPlatformPeiLib|ArmVirtPkg\Library\KvmtoolPlatformPeiLib\KvmtoolPlatformPeiLib.inf
