
[LibraryClasses.common]
  CacheAsRamLib|IntelFsp2Pkg\Library\BaseCacheAsRamLibNull\BaseCacheAsRamLibNull.inf
  CacheLib|IntelFsp2Pkg\Library\BaseCacheLib\BaseCacheLib.inf
  FspCommonLib|IntelFsp2Pkg\Library\BaseFspCommonLib\BaseFspCommonLib.inf
  FspPlatformLib|IntelFsp2Pkg\Library\BaseFspPlatformLib\BaseFspPlatformLib.inf
  FspSwitchStackLib|IntelFsp2Pkg\Library\BaseFspSwitchStackLib\BaseFspSwitchStackLib.inf

[LibraryClasses.IA32]
  DebugDeviceLib|IntelFsp2Pkg\Library\BaseDebugDeviceLibNull\BaseDebugDeviceLibNull.inf
  FspSecPlatformLib|IntelFsp2Pkg\Library\SecFspSecPlatformLibNull\SecFspSecPlatformLibNull.inf
