
[LibraryClasses.common.DXE_DRIVER]
  ShellLib|ShellPkg\Library\UefiShellLib\UefiShellLib.inf

[LibraryClasses.common.DXE_RUNTIME_DRIVER]
  HandleParsingLib|ShellPkg\Library\UefiHandleParsingLib\UefiHandleParsingLib.inf
  ShellCommandLib|ShellPkg\Library\UefiShellCommandLib\UefiShellCommandLib.inf
  ShellLib|ShellPkg\Library\UefiShellLib\UefiShellLib.inf

[LibraryClasses.common.UEFI_DRIVER]
  HandleParsingLib|ShellPkg\Library\UefiHandleParsingLib\UefiHandleParsingLib.inf
  AcpiViewCommandLib|ShellPkg\Library\UefiShellAcpiViewCommandLib\UefiShellAcpiViewCommandLib.inf
  BcfgCommandLib|ShellPkg\Library\UefiShellBcfgCommandLib\UefiShellBcfgCommandLib.inf
  ShellCEntryLib|ShellPkg\Library\UefiShellCEntryLib\UefiShellCEntryLib.inf
  ShellCommandLib|ShellPkg\Library\UefiShellCommandLib\UefiShellCommandLib.inf
  ShellLib|ShellPkg\Library\UefiShellLib\UefiShellLib.inf

[LibraryClasses.common.UEFI_APPLICATION]
  HandleParsingLib|ShellPkg\Library\UefiHandleParsingLib\UefiHandleParsingLib.inf
  AcpiViewCommandLib|ShellPkg\Library\UefiShellAcpiViewCommandLib\UefiShellAcpiViewCommandLib.inf
  BcfgCommandLib|ShellPkg\Library\UefiShellBcfgCommandLib\UefiShellBcfgCommandLib.inf
  ShellCEntryLib|ShellPkg\Library\UefiShellCEntryLib\UefiShellCEntryLib.inf
  ShellCommandLib|ShellPkg\Library\UefiShellCommandLib\UefiShellCommandLib.inf
  ShellLib|ShellPkg\Library\UefiShellLib\UefiShellLib.inf
