
[LibraryClasses.common.DXE_CORE]
  SecurityManagementLib|MdeModulePkg\Library\DxeSecurityManagementLib\DxeSecurityManagementLib.inf

[LibraryClasses.common.DXE_DRIVER]
  BootLogoLib|MdeModulePkg\Library\BootLogoLib\BootLogoLib.inf
  CustomizedDisplayLib|MdeModulePkg\Library\CustomizedDisplayLib\CustomizedDisplayLib.inf
  SecurityManagementLib|MdeModulePkg\Library\DxeSecurityManagementLib\DxeSecurityManagementLib.inf
  PlatformVarCleanupLib|MdeModulePkg\Library\PlatformVarCleanupLib\PlatformVarCleanupLib.inf
  UefiBootManagerLib|MdeModulePkg\Library\UefiBootManagerLib\UefiBootManagerLib.inf
  HiiLib|MdeModulePkg\Library\UefiHiiLib\UefiHiiLib.inf
  UefiHiiServicesLib|MdeModulePkg\Library\UefiHiiServicesLib\UefiHiiServicesLib.inf
  VariablePolicyLib|MdeModulePkg\Library\VariablePolicyLib\VariablePolicyLib.inf

[LibraryClasses.common.SMM_CORE]
  SmmCorePlatformHookLib|MdeModulePkg\Library\SmmCorePlatformHookLibNull\SmmCorePlatformHookLibNull.inf
  SmmServicesTableLib|MdeModulePkg\Library\PiSmmCoreSmmServicesTableLib\PiSmmCoreSmmServicesTableLib.inf

[LibraryClasses.common.DXE_RUNTIME_DRIVER]
  SecurityManagementLib|MdeModulePkg\Library\DxeSecurityManagementLib\DxeSecurityManagementLib.inf
  PlatformVarCleanupLib|MdeModulePkg\Library\PlatformVarCleanupLib\PlatformVarCleanupLib.inf
  UefiBootManagerLib|MdeModulePkg\Library\UefiBootManagerLib\UefiBootManagerLib.inf
  HiiLib|MdeModulePkg\Library\UefiHiiLib\UefiHiiLib.inf
  UefiHiiServicesLib|MdeModulePkg\Library\UefiHiiServicesLib\UefiHiiServicesLib.inf
  VarCheckLib|MdeModulePkg\Library\VarCheckLib\VarCheckLib.inf
  VariablePolicyLib|MdeModulePkg\Library\VariablePolicyLib\VariablePolicyLibRuntimeDxe.inf

[LibraryClasses.common.DXE_SMM_DRIVER]
  SecurityManagementLib|MdeModulePkg\Library\DxeSecurityManagementLib\DxeSecurityManagementLib.inf
  PlatformVarCleanupLib|MdeModulePkg\Library\PlatformVarCleanupLib\PlatformVarCleanupLib.inf
  HiiLib|MdeModulePkg\Library\UefiHiiLib\UefiHiiLib.inf
  UefiHiiServicesLib|MdeModulePkg\Library\UefiHiiServicesLib\UefiHiiServicesLib.inf
  VarCheckLib|MdeModulePkg\Library\VarCheckLib\VarCheckLib.inf
  VariablePolicyLib|MdeModulePkg\Library\VariablePolicyLib\VariablePolicyLib.inf

[LibraryClasses.common.UEFI_DRIVER]
  SecurityManagementLib|MdeModulePkg\Library\DxeSecurityManagementLib\DxeSecurityManagementLib.inf
  PlatformVarCleanupLib|MdeModulePkg\Library\PlatformVarCleanupLib\PlatformVarCleanupLib.inf
  UefiBootManagerLib|MdeModulePkg\Library\UefiBootManagerLib\UefiBootManagerLib.inf
  HiiLib|MdeModulePkg\Library\UefiHiiLib\UefiHiiLib.inf
  UefiHiiServicesLib|MdeModulePkg\Library\UefiHiiServicesLib\UefiHiiServicesLib.inf

[LibraryClasses.common]
  BmpSupportLib|MdeModulePkg\Library\BaseBmpSupportLib\BaseBmpSupportLib.inf
  FrameBufferBltLib|MdeModulePkg\Library\FrameBufferBltLib\FrameBufferBltLib.inf
  NonDiscoverableDeviceRegistrationLib|MdeModulePkg\Library\NonDiscoverableDeviceRegistrationLib\NonDiscoverableDeviceRegistrationLib.inf
  OemHookStatusCodeLib|MdeModulePkg\Library\OemHookStatusCodeLibNull\OemHookStatusCodeLibNull.inf
  ResetUtilityLib|MdeModulePkg\Library\ResetUtilityLib\ResetUtilityLib.inf
  VariablePolicyHelperLib|MdeModulePkg\Library\VariablePolicyHelperLib\VariablePolicyHelperLib.inf

[LibraryClasses.common.MM_STANDALONE]
  VarCheckLib|MdeModulePkg\Library\VarCheckLib\VarCheckLib.inf
  VariablePolicyLib|MdeModulePkg\Library\VariablePolicyLib\VariablePolicyLib.inf

[LibraryClasses.common.UEFI_APPLICATION]
  BootLogoLib|MdeModulePkg\Library\BootLogoLib\BootLogoLib.inf
  CustomizedDisplayLib|MdeModulePkg\Library\CustomizedDisplayLib\CustomizedDisplayLib.inf
  SecurityManagementLib|MdeModulePkg\Library\DxeSecurityManagementLib\DxeSecurityManagementLib.inf
  PlatformVarCleanupLib|MdeModulePkg\Library\PlatformVarCleanupLib\PlatformVarCleanupLib.inf
  UefiBootManagerLib|MdeModulePkg\Library\UefiBootManagerLib\UefiBootManagerLib.inf
  HiiLib|MdeModulePkg\Library\UefiHiiLib\UefiHiiLib.inf
  UefiHiiServicesLib|MdeModulePkg\Library\UefiHiiServicesLib\UefiHiiServicesLib.inf
