
[LibraryClasses.common.DXE_CORE]
  DxeCoreEntryPoint|MdePkg\Library\DxeCoreEntryPoint\DxeCoreEntryPoint.inf
  HstiLib|MdePkg\Library\DxeHstiLib\DxeHstiLib.inf
  DxeServicesLib|MdePkg\Library\DxeServicesLib\DxeServicesLib.inf
  UefiBootServicesTableLib|MdePkg\Library\UefiBootServicesTableLib\UefiBootServicesTableLib.inf
  UefiLib|MdePkg\Library\UefiLib\UefiLib.inf
  UefiRuntimeServicesTableLib|MdePkg\Library\UefiRuntimeServicesTableLib\UefiRuntimeServicesTableLib.inf

[LibraryClasses.common.SEC]
  ResourcePublicationLib|MdePkg\Library\PeiResourcePublicationLib\PeiResourcePublicationLib.inf

[LibraryClasses.common.PEIM]
  PeimEntryPoint|MdePkg\Library\PeimEntryPoint\PeimEntryPoint.inf
  ResourcePublicationLib|MdePkg\Library\PeiResourcePublicationLib\PeiResourcePublicationLib.inf

[LibraryClasses.common.DXE_DRIVER]
  HstiLib|MdePkg\Library\DxeHstiLib\DxeHstiLib.inf
  DxeServicesLib|MdePkg\Library\DxeServicesLib\DxeServicesLib.inf
  DxeServicesTableLib|MdePkg\Library\DxeServicesTableLib\DxeServicesTableLib.inf
  UefiBootServicesTableLib|MdePkg\Library\UefiBootServicesTableLib\UefiBootServicesTableLib.inf
  UefiDriverEntryPoint|MdePkg\Library\UefiDriverEntryPoint\UefiDriverEntryPoint.inf
  FileHandleLib|MdePkg\Library\UefiFileHandleLib\UefiFileHandleLib.inf
  UefiLib|MdePkg\Library\UefiLib\UefiLib.inf
  UefiRuntimeServicesTableLib|MdePkg\Library\UefiRuntimeServicesTableLib\UefiRuntimeServicesTableLib.inf
  UefiScsiLib|MdePkg\Library\UefiScsiLib\UefiScsiLib.inf
  UefiUsbLib|MdePkg\Library\UefiUsbLib\UefiUsbLib.inf

[LibraryClasses.common.SMM_CORE]
  DxeServicesLib|MdePkg\Library\DxeServicesLib\DxeServicesLib.inf
  DxeServicesTableLib|MdePkg\Library\DxeServicesTableLib\DxeServicesTableLib.inf
  SmmIoLib|MdePkg\Library\SmmIoLib\SmmIoLib.inf
  SmmMemLib|MdePkg\Library\SmmMemLib\SmmMemLib.inf
  UefiBootServicesTableLib|MdePkg\Library\UefiBootServicesTableLib\UefiBootServicesTableLib.inf
  UefiDriverEntryPoint|MdePkg\Library\UefiDriverEntryPoint\UefiDriverEntryPoint.inf
  UefiLib|MdePkg\Library\UefiLib\UefiLib.inf
  UefiRuntimeServicesTableLib|MdePkg\Library\UefiRuntimeServicesTableLib\UefiRuntimeServicesTableLib.inf

[LibraryClasses.common.DXE_RUNTIME_DRIVER]
  HstiLib|MdePkg\Library\DxeHstiLib\DxeHstiLib.inf
  DxeServicesLib|MdePkg\Library\DxeServicesLib\DxeServicesLib.inf
  DxeServicesTableLib|MdePkg\Library\DxeServicesTableLib\DxeServicesTableLib.inf
  UefiBootServicesTableLib|MdePkg\Library\UefiBootServicesTableLib\UefiBootServicesTableLib.inf
  UefiDriverEntryPoint|MdePkg\Library\UefiDriverEntryPoint\UefiDriverEntryPoint.inf
  FileHandleLib|MdePkg\Library\UefiFileHandleLib\UefiFileHandleLib.inf
  UefiLib|MdePkg\Library\UefiLib\UefiLib.inf
  UefiRuntimeLib|MdePkg\Library\UefiRuntimeLib\UefiRuntimeLib.inf
  UefiRuntimeServicesTableLib|MdePkg\Library\UefiRuntimeServicesTableLib\UefiRuntimeServicesTableLib.inf
  UefiScsiLib|MdePkg\Library\UefiScsiLib\UefiScsiLib.inf
  UefiUsbLib|MdePkg\Library\UefiUsbLib\UefiUsbLib.inf

[LibraryClasses.common.DXE_SMM_DRIVER]
  HstiLib|MdePkg\Library\DxeHstiLib\DxeHstiLib.inf
  DxeServicesLib|MdePkg\Library\DxeServicesLib\DxeServicesLib.inf
  DxeServicesTableLib|MdePkg\Library\DxeServicesTableLib\DxeServicesTableLib.inf
  SmmIoLib|MdePkg\Library\SmmIoLib\SmmIoLib.inf
  SmmMemLib|MdePkg\Library\SmmMemLib\SmmMemLib.inf
  SmmPeriodicSmiLib|MdePkg\Library\SmmPeriodicSmiLib\SmmPeriodicSmiLib.inf
  UefiBootServicesTableLib|MdePkg\Library\UefiBootServicesTableLib\UefiBootServicesTableLib.inf
  UefiDriverEntryPoint|MdePkg\Library\UefiDriverEntryPoint\UefiDriverEntryPoint.inf
  UefiLib|MdePkg\Library\UefiLib\UefiLib.inf
  UefiRuntimeServicesTableLib|MdePkg\Library\UefiRuntimeServicesTableLib\UefiRuntimeServicesTableLib.inf
  UefiScsiLib|MdePkg\Library\UefiScsiLib\UefiScsiLib.inf
  UefiUsbLib|MdePkg\Library\UefiUsbLib\UefiUsbLib.inf
  MmServicesTableLib|MdePkg\Library\MmServicesTableLib\MmServicesTableLib.inf
  SmmServicesTableLib|MdePkg\Library\SmmServicesTableLib\SmmServicesTableLib.inf

[LibraryClasses.common.UEFI_DRIVER]
  HstiLib|MdePkg\Library\DxeHstiLib\DxeHstiLib.inf
  DxeServicesLib|MdePkg\Library\DxeServicesLib\DxeServicesLib.inf
  DxeServicesTableLib|MdePkg\Library\DxeServicesTableLib\DxeServicesTableLib.inf
  UefiBootServicesTableLib|MdePkg\Library\UefiBootServicesTableLib\UefiBootServicesTableLib.inf
  UefiDriverEntryPoint|MdePkg\Library\UefiDriverEntryPoint\UefiDriverEntryPoint.inf
  FileHandleLib|MdePkg\Library\UefiFileHandleLib\UefiFileHandleLib.inf
  UefiLib|MdePkg\Library\UefiLib\UefiLib.inf
  UefiRuntimeServicesTableLib|MdePkg\Library\UefiRuntimeServicesTableLib\UefiRuntimeServicesTableLib.inf
  UefiScsiLib|MdePkg\Library\UefiScsiLib\UefiScsiLib.inf
  UefiUsbLib|MdePkg\Library\UefiUsbLib\UefiUsbLib.inf

[LibraryClasses.common]
  BaseLib|MdePkg\Library\BaseLib\BaseLib.inf
  OrderedCollectionLib|MdePkg\Library\BaseOrderedCollectionRedBlackTreeLib\BaseOrderedCollectionRedBlackTreeLib.inf
  PciCf8Lib|MdePkg\Library\BasePciCf8Lib\BasePciCf8Lib.inf
  S3IoLib|MdePkg\Library\BaseS3IoLib\BaseS3IoLib.inf
  S3PciLib|MdePkg\Library\BaseS3PciLib\BaseS3PciLib.inf
  S3PciSegmentLib|MdePkg\Library\BaseS3PciSegmentLib\BaseS3PciSegmentLib.inf
  S3SmbusLib|MdePkg\Library\BaseS3SmbusLib\BaseS3SmbusLib.inf
  S3StallLib|MdePkg\Library\BaseS3StallLib\BaseS3StallLib.inf
  SafeIntLib|MdePkg\Library\BaseSafeIntLib\BaseSafeIntLib.inf
  SynchronizationLib|MdePkg\Library\BaseSynchronizationLib\BaseSynchronizationLib.inf

[LibraryClasses.common.MM_STANDALONE]
  StandaloneMmDriverEntryPoint|MdePkg\Library\StandaloneMmDriverEntryPoint\StandaloneMmDriverEntryPoint.inf
  MmServicesTableLib|MdePkg\Library\StandaloneMmServicesTableLib\StandaloneMmServicesTableLib.inf

[LibraryClasses.common.UEFI_APPLICATION]
  HstiLib|MdePkg\Library\DxeHstiLib\DxeHstiLib.inf
  DxeServicesLib|MdePkg\Library\DxeServicesLib\DxeServicesLib.inf
  DxeServicesTableLib|MdePkg\Library\DxeServicesTableLib\DxeServicesTableLib.inf
  UefiApplicationEntryPoint|MdePkg\Library\UefiApplicationEntryPoint\UefiApplicationEntryPoint.inf
  UefiBootServicesTableLib|MdePkg\Library\UefiBootServicesTableLib\UefiBootServicesTableLib.inf
  FileHandleLib|MdePkg\Library\UefiFileHandleLib\UefiFileHandleLib.inf
  UefiLib|MdePkg\Library\UefiLib\UefiLib.inf
  UefiRuntimeServicesTableLib|MdePkg\Library\UefiRuntimeServicesTableLib\UefiRuntimeServicesTableLib.inf
  UefiScsiLib|MdePkg\Library\UefiScsiLib\UefiScsiLib.inf
  UefiUsbLib|MdePkg\Library\UefiUsbLib\UefiUsbLib.inf

[LibraryClasses.common.PEI_CORE]
  PeiCoreEntryPoint|MdePkg\Library\PeiCoreEntryPoint\PeiCoreEntryPoint.inf
