
[LibraryClasses.ARM]
  ArmSoftFloatLib|ArmPkg\Library\ArmSoftFloatLib\ArmSoftFloatLib.inf
  SemihostLib|ArmPkg\Library\SemihostLib\SemihostLib.inf

[LibraryClasses.common.DXE_CORE]
  DefaultExceptionHandlerLib|ArmPkg\Library\DefaultExceptionHandlerLib\DefaultExceptionHandlerLib.inf

[LibraryClasses.common.DXE_DRIVER]
  DefaultExceptionHandlerLib|ArmPkg\Library\DefaultExceptionHandlerLib\DefaultExceptionHandlerLib.inf

[LibraryClasses.common]
  ArmGicLib|ArmPkg\Drivers\ArmGic\ArmGicLib.inf
  ArmDisassemblerLib|ArmPkg\Library\ArmDisassemblerLib\ArmDisassemblerLib.inf
  ArmHvcLib|ArmPkg\Library\ArmHvcLib\ArmHvcLib.inf
  ArmLib|ArmPkg\Library\ArmLib\ArmBaseLib.inf
  ArmSvcLib|ArmPkg\Library\ArmSvcLib\ArmSvcLib.inf
  CompilerIntrinsicsLib|ArmPkg\Library\CompilerIntrinsicsLib\CompilerIntrinsicsLib.inf
  OpteeLib|ArmPkg\Library\OpteeLib\OpteeLib.inf
  StandaloneMmMmuLib|ArmPkg\Library\StandaloneMmMmuLib\ArmMmuStandaloneMmLib.inf

[LibraryClasses.AARCH64]
  SemihostLib|ArmPkg\Library\SemihostLib\SemihostLib.inf
