
[LibraryClasses.common.DXE_CORE]
  SmbiosLib|EmulatorPkg\Library\SmbiosLib\SmbiosLib.inf

[LibraryClasses.common.SEC]
  PpiListLib|EmulatorPkg\Library\SecPpiListLib\SecPpiListLib.inf

[LibraryClasses.common.USER_DEFINED]
  PpiListLib|EmulatorPkg\Library\SecPpiListLib\SecPpiListLib.inf

[LibraryClasses.common.DXE_DRIVER]
  SmbiosLib|EmulatorPkg\Library\SmbiosLib\SmbiosLib.inf

[LibraryClasses.common.SMM_CORE]
  SmbiosLib|EmulatorPkg\Library\SmbiosLib\SmbiosLib.inf

[LibraryClasses.common.DXE_RUNTIME_DRIVER]
  SmbiosLib|EmulatorPkg\Library\SmbiosLib\SmbiosLib.inf

[LibraryClasses.common.BASE]
  PpiListLib|EmulatorPkg\Library\SecPpiListLib\SecPpiListLib.inf

[LibraryClasses.common.DXE_SMM_DRIVER]
  SmbiosLib|EmulatorPkg\Library\SmbiosLib\SmbiosLib.inf

[LibraryClasses.common.UEFI_DRIVER]
  SmbiosLib|EmulatorPkg\Library\SmbiosLib\SmbiosLib.inf

[LibraryClasses.common]
  EmuThunkLib|EmulatorPkg\Library\DxeEmuLib\DxeEmuLib.inf
  KeyMapLib|EmulatorPkg\Library\KeyMapLibNull\KeyMapLibNull.inf

[LibraryClasses.common.UEFI_APPLICATION]
  SmbiosLib|EmulatorPkg\Library\SmbiosLib\SmbiosLib.inf
