
[LibraryClasses.common.DXE_DRIVER]
  FmpDependencyDeviceLib|FmpDevicePkg\Library\FmpDependencyDeviceLibNull\FmpDependencyDeviceLibNull.inf
  FmpPayloadHeaderLib|FmpDevicePkg\Library\FmpPayloadHeaderLibV1\FmpPayloadHeaderLibV1.inf

[LibraryClasses.common.UEFI_DRIVER]
  FmpDependencyDeviceLib|FmpDevicePkg\Library\FmpDependencyDeviceLibNull\FmpDependencyDeviceLibNull.inf
  FmpPayloadHeaderLib|FmpDevicePkg\Library\FmpPayloadHeaderLibV1\FmpPayloadHeaderLibV1.inf

[LibraryClasses.common]
  FmpDependencyLib|FmpDevicePkg\Library\FmpDependencyLib\FmpDependencyLib.inf

[LibraryClasses.common.UEFI_APPLICATION]
  FmpPayloadHeaderLib|FmpDevicePkg\Library\FmpPayloadHeaderLibV1\FmpPayloadHeaderLibV1.inf
