
[LibraryClasses.common.MM_CORE_STANDALONE]
  StandaloneMmCoreEntryPoint|StandaloneMmPkg\Library\StandaloneMmCoreEntryPoint\StandaloneMmCoreEntryPoint.inf

[LibraryClasses.AARCH64.MM_CORE_STANDALONE]
  MemLib|StandaloneMmPkg\Library\StandaloneMmMemLib\StandaloneMmMemLib.inf

[LibraryClasses.AARCH64.MM_STANDALONE]
  MemLib|StandaloneMmPkg\Library\StandaloneMmMemLib\StandaloneMmMemLib.inf

[LibraryClasses.IA32]
  FvLib|StandaloneMmPkg\Library\FvLib\FvLib.inf
